### ISSUE TITLE
Easiest way to have a link to download latest? 

### ISSUE THREAD

**Issue by jlperla** [xu-cheng/latex-action#10]
I am very excited to use the action, but I can't figure out a crucial component of the workflow...

My use case is that I always want to be able to get the latest pdfs from master from the latex builds, and easily link to them from the front README and for sending links to less technical coauthors. I don't care about versioning official releases, so what is most important is just a simple way to see the latest. 

- Lets say I follow a workflow similar to your https://github.com/xu-cheng/latex-action/blob/master/.github/workflows/test.yml

- Looks great, and at the bottom I could do `actions/upload-artifact@master`

- But now what? I know I, as a github action user, could click and download that asset, but that isn't a feasible way to link to the latest version of the document...
- any ideas on the easiest way to set up a way to link to download the latest? Is there an easy way to push it to a release, for example, or to link to the latest artifacts from the latest github action job?

**Comment by xu-cheng** [comment]
I would suggest you to push the pdf files to GitHub Pages and link them in the README file. 

You can follow a similar workflow in this repo: https://github.com/xu-cheng/latex-tutorial

**Comment by jlperla** [comment]
Thank you so much. That would be a great thing to highlight.

Sadly, my main need is for private repos while working on research. Any thoughts on that, as I don't believe github pages works with private? 

Or perhaps you can just publish to the ghpages branch, link to master of that, and not actually publish?

**Comment by xu-cheng** [comment]
With GitHub Actions, you can send the PDF files to anywhere you want. For your case, it depends on whether you want to make the pdf file public accessible. If not, you can just push it into a separated branch and link to it.

**Comment by jlperla** [comment]
@xu-cheng  (cc @arnavs) FYI: here is a set of instructions, which details the setup for pushing to a `docs` branch as you suggested.  This works with private repos: https://github.com/ubcecon/tutorials/blob/master/latex_actions.md
