### ISSUE TITLE
Dynamic source file name

### ISSUE THREAD

**Issue by kolosovpetro** [xu-cheng/latex-action#107]
Hej, is there any possibility to set root file name dynamically, through `env` block for example? I tried but got an error

https://github.com/kolosovpetro/github-latex-template/actions/runs/3348458591/jobs/5547536052

![image](https://user-images.githubusercontent.com/31904595/198730989-5267b033-68fd-4e7b-a4ec-efe0c4d0275c.png)

**Comment by xu-cheng** [comment]
You can use GitHub action expressions to achieve this. See https://docs.github.com/en/actions/learn-github-actions/expressions
