### ISSUE TITLE
Consider providing a sample for building Chinese documents.

### ISSUE THREAD

**Issue by ceciliachan1979** [xu-cheng/latex-action#112]
For a causal Latex user like me, trying to get some Chinese character to show up is getting really frustrating. It would be great if we can share a test on how to use extra-fonts or other means to achieve that.

For people who are also interested in getting Chinese character to work, [here](https://github.com/xu-cheng/latex-action/issues/74#issuecomment-1374949720) is a list of examples I tried that doesn't work.

Update: I have got it to work on my repo. The magic flag to get it to work is [here](https://github.com/ceciliachan1979/math/blob/bf828a99f36be93e6200c239dadbd03ae6937dfb/.github/workflows/blank.yml#L29).

**Comment by xu-cheng** [comment]
A PR is welcome. Importantly, the example should use free CJK fonts.
