### ISSUE TITLE
TeX Live 2023

### ISSUE THREAD

**Issue by eliabieri** [xu-cheng/latex-action#118]
Is there any plan to release an update that includes TeX Live 2023?

**Comment by xu-cheng** [comment]
Hi TeXLive 2023 will be available at Apr 1.

**Comment by xu-cheng** [comment]
Hi @sungwookson, yes it should be resolved at Apr 1 when the image will be updated to texlive 2023. However, the root cause of your issue is that you instruct the action to run `tlmgr update`, which is usually unnecessary. The docker image is updated once every month.
