### ISSUE TITLE
Use pinned version without forking

### ISSUE THREAD

**Issue by CCXXXI** [xu-cheng/latex-action#119]
I am aware that GitHub does not allow setting the base image as a runtime argument. But what if we maintain multiple version branches in this repo? The pinned version will then be usable as `xu-cheng/latex-action@20220801`.

Related: #113 #99 #88 #45

**Comment by xu-cheng** [comment]
Thanks for the suggestion. This is now supported. However, I choose to only support last three old versions of TeXLive.
