### ISSUE TITLE
"Build xu-cheng/latex-action@v2" occassionally takes 20+ minutes

### ISSUE THREAD

**Issue by hugobuddel** [xu-cheng/latex-action#120]
The second step in the latex action is building the Docker image. The output looks like this, with some of the hashes different each time:
```
Build container for action use: '/home/runner/work/_actions/xu-cheng/latex-action/v2/Dockerfile'.
  /usr/bin/docker build -t ed866e:24e714693ad84b499ecf4e755b52f78c -f "/home/runner/work/_actions/xu-cheng/latex-action/v2/Dockerfile" "/home/runner/work/_actions/xu-cheng/latex-action/v2"
  Sending build context to Docker daemon  20.48kB
  
  Step 1/3 : FROM ghcr.io/xu-cheng/texlive-full:latest
  latest: Pulling from xu-cheng/texlive-full
  f56be85fc22e: Already exists
  90c096d7ac30: Pulling fs layer
  90c096d7ac30: Verifying Checksum
  90c096d7ac30: Download complete
  90c096d7ac30: Pull complete
  Digest: sha256:00c731216c0bc0f5dda33a90ed2d8676fb7ca42a86bdde1386313e07d5c2b3c6
  Status: Downloaded newer image for ghcr.io/xu-cheng/texlive-full:latest
   ---> 9299b9c16e0c
  Step 2/3 : COPY   LICENSE   README.md   entrypoint.sh   /root/
   ---> e00d175929b6
  Step 3/3 : ENTRYPOINT ["/root/entrypoint.sh"]
   ---> Running in d79fae127ebf
  Removing intermediate container d79fae127ebf
   ---> d22cb29d2a87
  Successfully built d22cb29d2a87
  Successfully tagged ed866e:24e714693ad84b499ecf4e755b52f78c
```

Our latex CI usually takes about 4 minutes, about 2 minutes to build the Docker image, and 2 minutes to compile the latex document. Occasionally however, the above step takes more than 20 minutes. I'm not sure what the bottleneck is. Would it be possible to somehow speed this up?

Some hypotheses:
- The download of the texlive-full image is slow? Possible solution: perhaps make the image smaller somehow?
- Building the container is slow? Possible solution: perhaps create a separate image for latex-action?

Unfortunately the repository where I use latex-action is private, so I can't directly show the logs. (Although I could invite you to the project, that would be fine.) But related, it turns out that we ran out of the 2000 free CI minutes for private projects yesterday, which led me to investigate where the time was spent.

Not sure whether it is worthwhile to spend effort speeding this up, as the occasional 20 minutes is only problematic for private projects, and supporting those might be low priority. Nevertheless, I wanted to make note of this anyway. For our project, I'll just reduce the amount of CI runs we do.

**Comment by hugobuddel** [comment]
Ah, perhaps the github CI runner runs on different nodes/computers, and some of them would not (yet) have the texlive-full image cached (or not anymore). On those nodes it would have to download it first, while it is already cached on the others.

Putting a time limit on the CI would then probably not help, because that would prevent downloading the image, so it would never be cached, leading to even more failures. I'll just run it less often (or get the team to open up the project). (We also went over the MB limit for artifacts by having too many pdf artifacts.)

I'm not using any local runner, so I'm not sure how I can debug this, as this is the first step github action takes after setting up the runner, before any of my code runs. So by the time I could run `docker images`, the image would exist.

The image is only 2 GB (compressed) it seems, which seems about the right size for a full texlive image. So there is probably not much we could do to reduce the size. I'll therefore close the issue.

**Comment by xu-cheng** [comment]
Sorry, I mistook your previous comment, where I thought you are using a local runner. Since you are using Github official runner, the CI always starts in a clean environment. So in this case, the docker image is never cached. Downloading the whole image is already as fast it can be. 

Normally, the download should be relatively fast as both CI runner and the docker image should be in the same Github data center. But if there is any unstable network, you may see some slow down. Nevertheless, setting time out can definitely help to prevent using up the CI minutes due to transient slow network.
