### ISSUE TITLE
Unable to Increase Memory with `--extra-mem-top` and `--extra-mem-bot`

### ISSUE THREAD

**Issue by BikramHalder** [xu-cheng/latex-action#123]
I am facing trouble increasing the memory for pgfplots using `--extra-mem-top` and `--extra-mem-bot`. While these options work fine on my local system, they are not functioning as expected in the actions.

I have attempted to increase the memory size with the following arguments:

```yaml
args: -pdf -file-line-error --extra-mem-top=15000000 -interaction=nonstopmode
```
```yaml
args: -pdf -file-line-error --extra-mem-bot=15000000 -interaction=nonstopmode
```

However, both result in warnings:
```vbnet
pdflatex: unrecognized option `--extra-mem-top=15000000'
pdflatex: unrecognized option `--extra-mem-bot=15000000'
```

Consequently, the compilation process encounters the error:
```arduino
TeX capacity exceeded, sorry [main memory size=5000000].
```

This issue is halting the entire process. Any assistance would be highly appreciated.

Thank you.

**Comment by xu-cheng** [comment]
I don’t believe these flags are accepted by pdflatex. Are you sure that you can use these flags locally with pdflatex?

At the same time, the tex stackexchange suggests alternative solution for your problem, which you may want to try. https://tex.stackexchange.com/questions/7953/how-to-expand-texs-main-memory-size-pgfplots-memory-overload

**Comment by xu-cheng** [comment]
It seems that these flags you mentioned are only available in Miktex. So it is a Windows only thing. I suggest you try other more general solutions as mentioned above.

**Comment by BikramHalder** [comment]
Sorry, I didn't know that it's only available in MikTeX. Regarding the externalization of pgfplots, it is too clumsy to handle.
