### ISSUE TITLE
How can I pass variables to my latex command?

### ISSUE THREAD

**Issue by maxpowis** [xu-cheng/latex-action#124]
Hi,

My tex document can take optional arguments (i.e.: to generate a dark mode version)

The following commands work from the command line

```shell
# Generate the standard pdf
pdflatex mydoc
# Generate the pdf in dark mode
pdflatex "\def\darkmode{}\input{mydoc}"
```

I currently use latex-action for the standard pdf but I am not sure how to use it for the second scenario.
Can you help me figure out ?

**Comment by xu-cheng** [comment]
I would suggest you to create a mydoc-dark.tex file with the content you mentioned above. After that, you can simply compile mydoc-dark to generate the corresponding file. This has the additive benefit to compile documents in both standard and dark modes.

**Comment by maxpowis** [comment]
Awesome, thanks @xu-cheng. Followed you advise and got it working perfectly.
