### ISSUE TITLE
Fetching the action is very slow

### ISSUE THREAD

**Issue by giltho** [xu-cheng/latex-action#13]
Hello,

I have the simple workflow :
 - build latex document
 - push it by ssh to a server
 - slack me the new link

It runs in 3mn30, including 2mn30 just to build the latex-action image !

![image](https://user-images.githubusercontent.com/8451179/69824247-11bca900-1203-11ea-975e-120560d00f6f.png)

I have no idea how to make that faster, but it feels like it should be a tiny bit faster, given that the other actions build in less that 15s...

Thank you for your action !!

**Comment by xu-cheng** [comment]
The reason it takes so long is that the full texlive docker image is quite large about 2GB. The majority of time is used to download this image. 

I don't think there is much I can do to make it more faster. Though, if your latex document is relatively simple, you can try an old version of this action: `uses: xu-cheng/latex-action@1.1.0`. This will use a small texlive image with latex packages installed on the fly. If you found this old version is useful, I can add the support for small image back.

**Comment by giltho** [comment]
Ah indeed I understand... Well thank you for your answer, this still works perfectly well anyway
