### ISSUE TITLE
how to compile locally

### ISSUE THREAD

**Issue by guillaumeagile** [xu-cheng/latex-action#134]
to follow your instructions, I try to biuild localy the very simpled minted.tex alone using one dedicated yml file (as simple as what you give as an example in the REAMDE wih shell_escape set to true

to lunch the YML workflow on my compute (macOS M1), i use https://github.com/nektos/act
but i got this result
[Build LaTeX document/build_latex] 🚀  Start image=node:16-buster-slim
[Build LaTeX document/build_latex]   🐳  docker pull image=node:16-buster-slim platform= username= forcePull=true
[Build LaTeX document/build_latex]   🐳  docker create image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Build LaTeX document/build_latex]   🐳  docker run image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Build LaTeX document/build_latex]   ☁  git clone 'https://github.com/xu-cheng/latex-action' # ref=v3
[Build LaTeX document/build_latex] ⭐ Run Pre Compile LaTeX document
[Build LaTeX document/build_latex]   ✅  Success - Pre Compile LaTeX document
[Build LaTeX document/build_latex]   ☁  git clone 'https://github.com/actions/upload-artifact' # ref=v3
[Build LaTeX document/build_latex] ⭐ Run Main Set up Git repository
[Build LaTeX document/build_latex]   🐳  docker cp src=/Users/guillaume/SOURCES/Paper-ITICSE-latex/latex-action-iticse/. dst=/Users/guillaume/SOURCES/Paper-ITICSE-latex/latex-action-iticse
[Build LaTeX document/build_latex]   ✅  Success - Main Set up Git repository
[Build LaTeX document/build_latex] ⭐ Run Main Compile LaTeX document
[Build LaTeX document/build_latex]   🐳  docker cp src=/Users/guillaume/.cache/act/xu-cheng-latex-action@v3/ dst=/var/run/act/actions/xu-cheng-latex-action@v3/
[Build LaTeX document/build_latex] ⭐ Run Main "${GITHUB_ACTION_PATH}/action.sh" \
 🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1-composite-0.sh] user= workdir= (omitted)
 | /var/run/act/actions/xu-cheng-latex-action@v3/action.sh: line 7: docker: command not found
❌  Failure - Main "${GITHUB_ACTION_PATH}/action.sh" \

any clue?

what is your way to build locally any tex file using your action/docker image?

**Comment by xu-cheng** [comment]
It seems that you need to install and proper configure docker in your local environment.

**Comment by guillaumeagile** [comment]
no, Docker is running, look at the previous commands
![image](https://github.com/xu-cheng/latex-action/assets/197786/0ff2e2f3-e61a-4998-8799-f8cb384d7dbd)

**Comment by guillaumeagile** [comment]
it seems that locally, the env variable are not found
do I have to declare them somewhere?
 ❗  ::error::Unable to get ACTIONS_RUNTIME_TOKEN env variable

**Comment by zydou** [comment]
This action focused on using GitHub Actions Runner to build the tex project from the git repository. It is not recommended to use this action if you prefer building locally. Instead, you can directly pull the docker image to your local machine and mount your project into the container to build your project locally.

```sh
docker pull ghcr.io/xu-cheng/texlive-full:latest
cd /path/to/your/tex_project

# This will launch a interactive shell in the container, you can run custom commands in the container to build your project.
docker run --rm -it -v $(pwd):/src -w /src ghcr.io/xu-cheng/texlive-full:latest bash

# Or, if you prefer to run a single command, you can use the following command.
docker run --rm -it -v $(pwd):/src -w /src ghcr.io/xu-cheng/texlive-full:latest latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode main.tex
```

The docker image `ghcr.io/xu-cheng/texlive-full` only has the `amd64` architecture. If you use an `arm64` machine (e.g. MacBook with M1 chip or newer), you could try [this image](https://github.com/zydou/texlive) with `arm64` support.

```sh
docker pull zydou/texlive:latest
cd /path/to/your/tex_project

# This will launch a interactive shell in the container, you can run custom commands in the container to build your project.
docker run --rm -it -v $(pwd):/src -w /src zydou/texlive:latest bash

# Or, if you prefer to run a single command, you can use the following command.
docker run --rm -it -v $(pwd):/src -w /src zydou/texlive:latest latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode main.tex
```

Alternatively, if you use VS Code to edit your tex project, I recommend using this devcontainer template: [zydou/latex-template](https://github.com/zydou/latex-template). It is specifically designed for writing latex in VS Code locally.

**Comment by xu-cheng** [comment]
Since this action works as intended on GitHub, I believe your issue comes from the act tool. Please consider to raise the issue to them. If some changes in my side can help to address the problem, a PR is welcomed. However, running this action using act is not directly supported.
