### ISSUE TITLE
latest Install font ./fonts/EB\033[0m cp: can't stat './fonts/EB\': No such file or directory

### ISSUE THREAD

**Issue by Moelf** [xu-cheng/latex-action#136]
There seems to be some bug related to parsing `extra_fonts` path, here's what I have in the ci yaml:

```
        with:
          ...
          extra_fonts: |
            ./fonts/EB\ Garamond/*
            ./fonts/Source\ Code\ Pro/*
            ./fonts/Lato/*
```

**Comment by Moelf** [comment]
this works on 2.8.0, I suspect it was broken by 2.8.2:

https://github.com/xu-cheng/latex-action/compare/2.8.0...2.8.2#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R128

**Comment by xu-cheng** [comment]
Hi, can you may be try the following?
```yaml
with:
  extra_fonts: |
    ./fonts/EB Garamond/*
    ./fonts/Source Code Pro/*
    ./fonts/Lato/*
```

Also, it is generally recommended to not have space in the path.
