### ISSUE TITLE
Caching Docker image?

### ISSUE THREAD

**Issue by TheChilliPL** [xu-cheng/latex-action#137]
How would one go about caching a Docker image? Downloading it every time makes the compilation slow overall, even when caching auxiliary files. Caching Docker image could improve its download time, thus significantly improving the overall compilation time.

**Comment by xu-cheng** [comment]
Hi, the docker image is already stored in Github server. So caching docker image would have zero benefit since the github action is always running in a fresh VM. There is no difference between downloading cached image or the image from github servers.
