### ISSUE TITLE
supporting extra fonts' cache

### ISSUE THREAD

**Issue by MohammadRaziei** [xu-cheng/latex-action#138]
hi, every time I run this action, it installs the fonts that I mentioned as extra fonts.
so it installs them and clears caches with fc-cache.
I think this is not a good idea. because it happend every time.
can you cache the extra fonts? or help me to use [this action](https://github.com/actions/cache) to combine it with your action to reduce the time of building.

**Comment by xu-cheng** [comment]
Hi, if you are compiling multiple files, the font installation will only happen once. Otherwise, fonts need to be installed for each fresh CI run. If you really want to avoid this, please consider to use a custom docker image with fonts pre-installed. See the doc on how to use custom docker image with this action.

**Comment by MohammadRaziei** [comment]
fine, but can you help me to use https://github.com/actions/cache to cache the fonts directory? so in the next run, it restores the fonts directory and we doesn't need to download it again. we can use the hash of fonts directory as a part of restore key. but I have no more idea how to use it for your action

**Comment by xu-cheng** [comment]
The [cache](https://github.com/actions/cache) action won't work. Because this action works in a docker container. Moreover, I saw you only compile one document. In that case, it is no pointed to cache the font installation (of course, you can cache the font download step.)

**Comment by MohammadRaziei** [comment]
can I remove fc-cache command after installing fonts? as I know it can help in some cases where installed fonts not recognized. maybe with disabling this command we get the output as well

**Comment by xu-cheng** [comment]
Sorry, I don't understand what you want to achieve. Please use `pre_compile` option if you want to customize your setup.
