### ISSUE TITLE
ERROR - Error: Found biblatex control file version 3.11, expected version 3.10.

### ISSUE THREAD

**Issue by wzh4464** [xu-cheng/latex-action#145]
Hi.

Thank you for your github action very much.

However, I encounter a bilatex version conflict using your action. 

`ERROR - Error: Found biblatex control file version 3.11, expected version 3.10.` is what I can see from the output of the action.

[https://github.com/wzh4464/big-cocluster-paper.git](url) is the repository facing this error and if you are interested, I can provide more details.

The files are well compiled locally, maybe since I update all packages at once locally.

Thank you for your concern!

**Comment by xu-cheng** [comment]
This seems to be caused by out-of-sync of biber and biblatex in the latest docker image. I have roll backed the image to the last working one. Please try again. The issue should have been resolved.

**Comment by wzh4464** [comment]
Problem solved. Thank you very much for your quick response and voluntary commitment.

**Comment by hugobuddel** [comment]
I'm currently getting this error. I resolved it by explicitly using the working docker image:
```
          docker_image: ghcr.io/xu-cheng/texlive-full:20240315
```

**Comment by xu-cheng** [comment]
This seems to be upstream issue, which I have reported at https://github.com/plk/biber/issues/476

In the meaning, the default image has been reverted back to the last working one.
