### ISSUE TITLE
Pushing PDF to gh-pages branch

### ISSUE THREAD

**Issue by lorenzoFabbri** [xu-cheng/latex-action#151]
Hello. I read on the README that it is possible to push the resulting PDF to the gh-pages branch but I am having some difficulties achieving that. My YML file is available [here](https://github.com/lorenzoFabbri/causal-effects-id/blob/main/.github/workflows/main.yml). I get several errors, including one saying that the PDF file is not found:

<img width="1545" alt="image" src="https://github.com/xu-cheng/latex-action/assets/22343884/621c403f-4bfd-4f57-a4c4-480a54a9b83f">

**Comment by xu-cheng** [comment]
Closed as it is not related to this action. Please search google or other communities like Reddit to solve general problem of GitHub actions.
