### ISSUE TITLE
Action breaks if there are spaces in the root_file name

### ISSUE THREAD

**Issue by JeromSar** [xu-cheng/latex-action#154]
Hello!

Thank you for making this amazing action. It works perfectly, except that there's a bug if the filepath in the `root_file` parameter contains a space. It will then take everything before the space, and treat that as the full path.

Possible to fix with a few quotes? Adding quotes to the `root_file` does not seem to fix the problem.

Appreciate any help you could provide.

**Comment by xu-cheng** [comment]
It’s generally strongly recommended to not have space in the filename in LaTeX ecosystem. Many LaTeX tools and package will break due to the space in the path. So, I think it’s better for you to avoid the space in the first place.

**Comment by JeromSar** [comment]
Thanks, clear
