### ISSUE TITLE
libpng: internal error

### ISSUE THREAD

**Issue by Kakashiiiiy** [xu-cheng/latex-action#18]
I've tried to compile my files but I've got a libpng error. On my local machine (Arch) everything works flawless. Is this error caused by Ubuntu's libpng version
```
 [Loading MPS to PDF converter (version 2006.09.02).]
 ) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
 libpng error: Not a PNG file
 (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
 !pdfTeX error: pdflatex (file ../Vorlage/hgi_nds_1.png): libpng: internal error
 
  ==> Fatal error occurred, no output PDF file produced!
 Collected error summary (may duplicate other messages):
 === TeX engine is 'pdfTeX'
   pdflatex: Command for 'pdflatex' gave return code 1
       Refer to 'auswertung_9.log' for details
```
And the error is not caused by the special picture, I already commented it out and all other pictures cause the error as well.

**Comment by xu-cheng** [comment]
Please check the file `../Vorlage/hgi_nds_1.png` is indeed a valid png file.

Please show a minimal working example to demonstrate your problem.

**Comment by Kakashiiiiy** [comment]
I've made a short vid to demonstrate it works flawless on my PC. In the video hdi_nds_1.png is commented out at compile time but it doesn't matter because the build fails then at the second image with the same error on Github. 

[here ist the video](https://www.youtube.com/watch?v=GArtQ-G9eMw).

**Comment by xu-cheng** [comment]
Please read https://tex.meta.stackexchange.com/questions/3300/minimum-working-example-mwe on how to write a proper minimal working example.

**Comment by Kakashiiiiy** [comment]
I've created a mwe under https://github.com/Kakashiiiiy/latex_test

**Comment by Kakashiiiiy** [comment]
Ahh I know what is causing the error. I am using Git-LFS for the files. If it is not installed the files are not recognized correctly and therefore the build fails. Is there a way to manually install it?

**Comment by Kakashiiiiy** [comment]
But I have no idea how to fix this....
