### ISSUE TITLE
How can I use 'pLaTeX2e'?

### ISSUE THREAD

**Issue by akikirinrin** [xu-cheng/latex-action#26]
Hi,

Thank you for making great action!
I managed to compile simple tex file, but failed to compile .tex with multi-byte characters.

Reading `README.md`, I gave option `"-xelatex -file-line-error -interaction=nonstopmode"` to `arg` of the action, but got errors below: 

```
Latexmk: applying rule 'xelatex'...
15
Running 'xelatex -no-pdf -file-line-error -interaction=nonstopmode -recorder  "paper/manuscript.tex"'
16
------------
17
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
18
 restricted \write18 enabled.
19
entering extended mode
20
(./paper/manuscript.tex
21
LaTeX2e <2020-02-02> patch level 5
22
L3 programming layer <2020-02-25>
23
(/opt/texlive/texdir/texmf-dist/tex/platex/jsclasses/jsarticle.cls
24

25
/opt/texlive/texdir/texmf-dist/tex/platex/jsclasses/jsarticle.cls:26: LaTeX Err
26
or: This file needs format `pLaTeX2e'
27
               but this is `LaTeX2e'.
```

Would you advise me how can I run `pLaTeX2e` on Docker?

Thanks,

**Comment by xu-cheng** [comment]
You need to use `uplatex` or `platex` instead of `XeLaTeX`.

**Comment by akikirinrin** [comment]
Thank you for your quick reply.

This issue was fixed after I added `compiler: uplatex`.
Although I'm still having an error, I'll try to debug by myself.

Thank you so much!

**Comment by xu-cheng** [comment]
You may consider to use uplatex in conjunction with latexmk. This can be done by changing `args` input or creating latexmkrc file. For more information, you can read latexmk doc or google. There is also https://texwiki.texjp.org/?Latexmk

**Comment by akikirinrin** [comment]
Thank you so much.
I managed to  typeset and upload .pdf!!

```
with:
   root_file: paper/manuscript.tex
   args: "-latex=platex -pdfdvi -file-line-error -interaction=nonstopmode"
```

Now I'm fighting with blank pdf 😅

Please excuse me ifI open another Issue...

Thank you!

**Comment by akikirinrin** [comment]
I succeeded to build my pdf by creating `.latexmkrc` at the same directory with the `.tex` file.

Thank you so much!! :smile:
