### ISSUE TITLE
Upgrade the import package

### ISSUE THREAD

**Issue by amirc** [xu-cheng/latex-action#28]
Hi,
Thanks for sharing this great action.
There is a bug with subfiles package together with import v6.0 that was solved on import v6.1 (see https://github.com/gsalzer/subfiles/issues/6)
Can I add a parameter to upgrade this package?

Thanks,
Amir.

**Comment by xu-cheng** [comment]
The TeXLive docker image is set to be updated automatically every first day of the month. So your problem should be fixed in a few days. Notably, it will upgrade to TeXLive 2020 in next month.

If it is requested, I can add a new feature for this action to update its packages on-the-fly.

**Comment by amirc** [comment]
Indeed, there is much time to wait.
I don't know what the importance of such a feature is, but I would have used it.

Thanks again!

**Comment by xu-cheng** [comment]
The TeXLive image has been updated. This problem should have been solved.
