### ISSUE TITLE
How to fix "Unknown message 'unsupported-engine'"?

### ISSUE THREAD

**Issue by Jeff-Tian** [xu-cheng/latex-action#3]
我在尝试使用 latex-action 来编译基于 fduthesis 写的 document，碰到错误：

```
Unknown message 'unsupported-engine' for module 'fduthesis'.
```

![image](https://user-images.githubusercontent.com/3367820/65386846-04062580-dd73-11e9-85b3-872750bd345b.png)

可否帮忙排查是哪里的问题，应该怎么解决？

完整错误信息在这里：https://github.com/Jeff-Tian/thesis-paper/commit/88105929197a30dda4a18ccf46b5bc9e95e4c318/checks

配置在这里：

https://github.com/Jeff-Tian/thesis-paper/blob/master/.github/workflows/blank.yml

谢谢！

**Comment by xu-cheng** [comment]
By default, this action uses pdfLaTeX to compile the document. For language other than English, it is common (or required as in your case) to use XeLaTeX or LuaLaTeX. 

To do that, you should set the args to `-xelatex -file-line-error -interaction=nonstopmode` or `-lualatex --file-line-error --interaction=nonstopmode` respectively. Alternatively, you could create a `.latexmkrc` file.
