### ISSUE TITLE
access to github clone/push denied inside docker

### ISSUE THREAD

**Issue by shahdloo** [xu-cheng/latex-action#34]
I acknowledge it is not directly related to this action, but I appreciate your input:
I aimed to do clone->copy pdf->commit->push inside the action, after build completed, in order to update a pdf in my gh-pages repo without the need to download and push the artifact manually. It seems that github blocks access to repo with "Permission denied (publickey)", although I can confirm that I can clone/push with the same private key normally. 
Any suggestions for this?
<https://github.com/shahdloo/shahdloo.github.io/blob/master/.github/workflows/cv.yml>
<https://github.com/shahdloo/shahdloo.github.io/runs/911449174?check_suite_focus=true>

**Comment by sosiristseng** [comment]
Hi maybe you want to check out this publish to `gh-pages` action: <https://github.com/marketplace/actions/github-pages-action>

**Comment by xu-cheng** [comment]
I think your problem is due to `DEPLOY_KEY` not being set. Note that the env lines are commented. 

```yaml
#       env:
#         DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
```

I will close the issue, since it is not relevant to the GitHub Action. Please ask similar questions in StackOverflow or https://github.community in the future.
