### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by FliiFe** [xu-cheng/latex-action#36]
Github CI workflows are failing because the texlive-full docker image does not seem to get built correctly. Here's the relevant part from the logs

```
  Step 1/3 : FROM ghcr.io/xu-cheng/texlive-full:latest
  latest: Pulling from xu-cheng/texlive-full
  df20fa9351a1: Pulling fs layer
  b57c08061e57: Pulling fs layer
  error pulling image configuration: unknown blob
  ##[warning]Docker build failed with exit code 1, back off 1.961 seconds before retry.
```

I had no luck with `@v2`, `@2.2.0` and `@master`. The same happens with `texlive-action@master`.

**Comment by xu-cheng** [comment]
Can you retry your workflow again? Looks like that it was an issue of the GitHub Container Registry. I just verified that the action works fine now.

If the problem persists, you need to contact the Github Supports.

**Comment by FliiFe** [comment]
Yup, works !
Apologies for the inconvenience
