### ISSUE TITLE
Docker build failed with exit code 1

### ISSUE THREAD

**Issue by florian30491** [xu-cheng/latex-action#37]
![image](https://user-images.githubusercontent.com/58624223/94009504-d5b38f80-fda4-11ea-8a68-7d11833e7967.png)

Can I get any help from you @xu-cheng about this problem?

**Comment by znewman01** [comment]
Duplicate of #36?

**Comment by florian30491** [comment]
I didn't see this issue. After restarting the action everything went fine.
