### ISSUE TITLE
Biber support in Github Action

### ISSUE THREAD

**Issue by florianbaer** [xu-cheng/latex-action#38]
Hi 
Thanks for your work so far!
It would be nice to support to run latex build with the '-biber' argument. Is this possible to implement in the near future?

**Comment by xu-cheng** [comment]
This action uses latexmk by default, which should support biber automatically. 

Please refer to [latexmk doc](http://texdoc.net/texmf-dist/doc/support/latexmk/latexmk.pdf) for more detail. 

If you have any trouble, please show a minimal example.
