### ISSUE TITLE
How to copy `texlive-fontconfig.conf` file?

### ISSUE THREAD

**Issue by Jeff-Tian** [xu-cheng/latex-action#4]
Thank you for helping me about the #3 . Now I am still struggling with compile the `fduthesis` package. Now it failed at :  
```
Package fontspec Error: The font "XITS-Regular" cannot be f
ound.
```

I googled and found the solution here: https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-340003.4.4
![image](https://user-images.githubusercontent.com/3367820/65404973-6f043a80-de0d-11e9-95b4-69c444f3dd88.png)

## Help wanted:

How can I copy the `texlive-fontconfig.conf` file? I tried the following paths:
```
cp /root/texlive/texmf-var/fonts/conf/texlive-fontconfig.conf ...
cp /opt/textlive/texmf-var/fonts/conf/texlive-fontconfig.conf ...
```

but with no luck:

```
cannot access '/root/texlive/texmf-var': Permission denied
cannot access '/opt/texlive/': No such file or directory
```

**Comment by xu-cheng** [comment]
"XITS-Regular" seems to come from package `xits`. Could you try to add `xits` in to the `extra_packages`?

**Comment by xu-cheng** [comment]
FYI, the most common reason for this action to fail is that `texliveonfly` fails to find the missing package. So you could try to find and add them to the `extra_packages`. Sometimes, you can use `tlmgr search <keyword>` in your local environment to find the package.

**Comment by Jeff-Tian** [comment]
@xu-cheng Thanks for the help, by adding  `xits` package to `extra_packages` the error was fixed.
