### ISSUE TITLE
Suddenly getting auto expansion error

### ISSUE THREAD

**Issue by Zethson** [xu-cheng/latex-action#42]
Hi,

my workflow, which build my thesis is suddenly broken.
I did not touch the tex code for a couple of months.

Suddenly getting: `./thesis.tex:112: pdfTeX error (font expansion): auto expansion is only possible with scalable fonts.`

Did you change anything? Do you have any idea?
Again, I did not touch the tex and it works for me locally.

**Comment by xu-cheng** [comment]
I am not sure whether it is related to https://github.com/xu-cheng/latex-action/issues/41. Can you retry the workflow again? 

If it still reports the error, please show a [minimal working example to reproduce your problem](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that).

**Comment by Zethson** [comment]
Working again now.

So I guess it is.
