### ISSUE TITLE
Caching docker image

### ISSUE THREAD

**Issue by Damix48** [xu-cheng/latex-action#44]
Is it possible caching the docker image to speed up the build process?

**Comment by xu-cheng** [comment]
If you mean caching docker image between multiple documents in the same workflow, it is already the case. Otherwise, there is nothing we can do. The workflow has to download the docker image in the beginning of the task.

**Comment by aadibajpai** [comment]
> If you mean caching docker image between multiple documents in the same workflow, it is already the case. Otherwise, there is nothing we can do. The workflow has to download the docker image in the beginning of the task.

github actions have an inbuilt cache that persists between workflows, maybe you've seen it and it doesn't work here but just in case https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows, it might be useful in reducing build times even if it's something that could be done by the user in their workflow.

**Comment by xu-cheng** [comment]
Sorry, there is simply no point to cache the docker image. The cache is used to speed up process when there are redundant computation. We don't have such a thing here. There is no difference in term of time between downloading from docker registry and downloading from cache.

Also, you cannot cache docker image using cache in Github action.

**Comment by aadibajpai** [comment]
> Sorry, there is simply no point to cache the docker image. The cache is used to speed up process when there are redundant computation. We don't have such a thing here. There is no difference in term of time between downloading from docker registry and downloading from cache.
> 
> Also, you cannot cache docker image using cache in Github action.

I see, thanks for the clarification.
