### ISSUE TITLE
Compile multiple LaTeX projects

### ISSUE THREAD

**Issue by ToldoDM** [xu-cheng/latex-action#46]
Is there a way to compile multiple LaTeX projects?

Let me explain with an example.

I have a repo like this:
- Folder1/
   - Project1/
      - main.tex
      - res/
         - resource.tex
    - Project2/
      - main.tex
      - res/
         - resource.tex
- README.md
- .gitignore

Is there a way to tell the action to search into `Folder1` (like the declaration of the working folder) and compile each `main.tex` of each project?
Obviously the main file will have always the same name, in this case `main.tex`.

**Comment by xu-cheng** [comment]
I would suggest you to have a Makefile or similar build scripts in your project to compile all the latex documents. Then, you can use https://github.com/xu-cheng/texlive-action in your GitHub action. This also comes with the benefit that helps you compiling documents easily locally.

**Comment by ToldoDM** [comment]
Thank you, that's very helpful
