### ISSUE TITLE
Compile last pushed file

### ISSUE THREAD

**Issue by Neskelogth** [xu-cheng/latex-action#47]
I have to compile the some tex files, but there is not a fixed number of them and i have no guarantee that the last one that was pushed is a new file. Is there a way to identify the last pushed file and compile only that one?

**Comment by xu-cheng** [comment]
Sorry, but this is outside the scope of the action. You can write your script using git to find the file and pass it to this action using [github action output](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter). Moreover, you may want to use https://github.com/xu-cheng/texlive-action Instead if you need to compile multiple documents.
