### ISSUE TITLE
tikz-uml.sty and pgfopts.sty are missing

### ISSUE THREAD

**Issue by krook1024** [xu-cheng/latex-action#51]
I am using this action for compiling my thesis and being a Computer Science student, I have to present some UML diagrams. For such tasks, I have always resorted to the [tikz-uml package](https://perso.ensta-paris.fr/~kielbasi/tikzuml/var/files/doc/tikzumlmanual.pdf), but I can not seem to get it working with this action. Is there any way I can install the files listed below, and have my LaTeX compilation working again?

- tikz-uml.sty
- pgfopts.sty

**Comment by xu-cheng** [comment]
These packages don't seem to come with TeXLive. You have to install them by yourself. For example, you can simply put `*.sty` files in the same directory of the main tex file.
