### ISSUE TITLE
LaTeX file not found

### ISSUE THREAD

**Issue by dpo** [xu-cheng/latex-action#58]
What am I doing wrong here? The main document is under the folder `paper` but `latexmk` complains that it can't find it.

Here's a link to the error: https://github.com/dpo/paper-latex-action/runs/2635109552?check_suite_focus=true#step:6:29

It appears that the tex document is present: https://github.com/dpo/paper-latex-action/runs/2635109552?check_suite_focus=true#step:5:76

Here's the config: https://github.com/dpo/paper-latex-action/blob/main/.github/workflows/build-latex.yml

Thanks in advance!

**Comment by xu-cheng** [comment]
Can you try to compile it locally by `latexmk -pdf paper-latex-action.tex`?

It looks that it is an issue in your latex file.

**Comment by xu-cheng** [comment]
I also noticed that you have `\bibliography{abbrv,\jobname}` in your tex file. This would be translated to `\bibliography{abbrv, paper-latex-action.tex}`. It doesn’t look right.

**Comment by dpo** [comment]
The compilation goes fine locally. `jobname` is translated to the tex file name without the extension. That's legit.

**Comment by dpo** [comment]
Also note that the error is that the file is not found.

**Comment by dpo** [comment]
The error is the same if I replace `\jobname`: https://github.com/dpo/paper-latex-action/runs/2635383166?check_suite_focus=true#step:6:38

**Comment by xu-cheng** [comment]
> `TEXINPUTS: ${{ github.workspace }}`

This seems to be the culprit. If you need add path to  `TEXINPUTS`, it should be something like `TEXINPUTS: .:${{ github.workspace }}`

**Comment by xu-cheng** [comment]
You may want to try compile it locally with `TEXINPUTS` env. Something like: `TEXINPUTS=somevar latexmk -pdf paper-latex-action.tex`

**Comment by xu-cheng** [comment]
Also, I just find out that you should not use `github.workspace` in `TEXINPUTS`.

This action works in a separated docker container, where the relevant files are mirrored into it. So it would be better to use relative path like: `TEXINPUTS: .:./some/folder/` or use `PWD` like: `TEXINPUTS: .:$PWD/some/folder/`.

**Comment by dpo** [comment]
Yes, that is the problem indeed. Now I'm getting further, but
```
LaTeX Error: File `amsmath.sty' not found.
```

**Comment by xu-cheng** [comment]
You need to add an trailing colon in `TEXINPUTS`. See my comment https://github.com/dpo/paper-latex-action/commit/50e4a75f075665eb411b94965c43d910b5f40216#r51103370

**Comment by dpo** [comment]
Well, you're right. I'm aware of the trailing colon. I tried it before but it results in the workflow not even running:
```
.github/workflows/build-latex.yml#L32
You have an error in your yaml syntax on line 32
```

**Comment by xu-cheng** [comment]
Can you try to quote it? Like 
```yaml
env:
    TEXINPUTS: ".:./some/folder/:"
```

**Comment by xu-cheng** [comment]
Please let me know whether the problem is fixed to you. In the mean time, I added a new FAQ entry in the README on how to use TEXINPUTS: https://github.com/xu-cheng/latex-action#how-to-add-additional-paths-to-the-latex-input-search-path

**Comment by dpo** [comment]
Success at last! Many thanks for your help. Another useful trick to remember with TEXINPUTS is that if you want to include all subfolders of a given folder, you need to use a double slash:
```
TEXINPUTS: ".:$PWD/../siam-styles:$PWD/../latex-styles-master/styles//:"
```
