### ISSUE TITLE
Error: Container action is only supported on Linux

### ISSUE THREAD

**Issue by vikaskumar30** [xu-cheng/latex-action#59]
Hi,
I am currenly running a github action compiling a latex document on a self-hosted windows runner and getting the above error. Is this not supported on windows based runner?

the section related to latex in the action yaml file is below:

-  name: Compile latex document
    uses: xu-cheng/latex-action@v2
    with:
       root_file: main.tex
       latexmk_shell_escape: true
       latexmk_use_lualatex: true

**Comment by xu-cheng** [comment]
This action relies docker container to work. It seems that you have to use a self-hosted Linux runner. Alternatively, you could try to use the Linux runner in WSL.

I will close the issue for now, as it is out scope of this action. If you have further issue of using docker in self-hosted Github Action runner, I suggest to ask support from Github.
