### ISSUE TITLE
Compatibility issues with updated siunitx package

### ISSUE THREAD

**Issue by siemdejong** [xu-cheng/latex-action#62]
I'm experiencing issues when using this Github Action with the updated siunitx package. Quantities and units are now typeset using \qty and \unit, but this action doesn't allow the use of these commands and throws the error
```
Undefined control sequence.
l.51 where $x = \qty
```
The package is loaded in the preamble, but my guess is that it's not updated. Is it possible to update the package?

**Comment by xu-cheng** [comment]
The docker image is updated monthly. If you want to make sure the package is always up-to-date. You can add `pre_compile: "tlmgr update --self && tlmgr update --all"` in your workflow. Or `pre_compile: "tlmgr update --self && tlmgr update <pkg>"`  to update selected packages.
