### ISSUE TITLE
Source citation in the appendix crashes the Action

### ISSUE THREAD

**Issue by Zeyecx** [xu-cheng/latex-action#66]
Hello. 
I have used bibtex to manage my references. However, the action always crashes for me. If I compile the file locally, it works. 
Herewith I create the source list. 
```latex
\cleardoublepage
\ihead[]{Literaturverzeichnis}
\bibliographystyle{alphadin}
\bibliography{literatur}
```

The literature is also found. Nevertheless, it is stated that all elements are not found. In the Bibtex everything is also correct. Here is an example.  

```bibtex
@ARTICLE {facharbeit,
    author   = "Julian von Mendel",
    title    = "RSA-Verschluesselung",
    year     = "2009",
    volume   = "1",
    pages    = "9-13",
    month    = "jan",
    crossref = "https://derjulian.net/resources/facharbeit.pdf"
```

In the Latex Document I call this as follows. 
```latex
\cite{facharbeit}
```

Since it works locally I assume that it does. That my latex code works. What do they say. If you want, I can show you a complete protocol.

**Comment by xu-cheng** [comment]
Please show a minimum work example and the build logs for your problem.

**Comment by xu-cheng** [comment]
I think the problem comes from your project not this action. If you test locally through command line like `latexmk -pdf test` or `pdflatex test && bibtex test && pdflatex test && pdflatex test`, you will see that it actually failed to compile. You IDE may force to compile the document so it would seem that the compilation succeed.

**Comment by Zeyecx** [comment]
Hi. Thanks for the answer. I have actually tried it out. First I removed everything.
![image](https://user-images.githubusercontent.com/15014849/125871275-40c6d54c-dc7b-460f-8184-1eec3c09deab.png)
After that I tried your command. 
![image](https://user-images.githubusercontent.com/15014849/125871330-fc5c895b-5b6a-4c91-a826-05be2e5bef78.png)
In fact, it fails. Just as you predicted. However, ironically, it still created the PDF. 
![image](https://user-images.githubusercontent.com/15014849/125871434-35678a68-b296-414f-b82a-30a9f9277d5e.png)

**Comment by Zeyecx** [comment]
With the following command, there is not even an error message.
```shell
pdflatex -synctex=1 -interaction=nonstopmode "test.tex"
```

**Comment by xu-cheng** [comment]
I tried your project locally it failed at bibtex. You can see by running `latexmk -pdf test && echo $?`

**Comment by xu-cheng** [comment]
Your issue comes from bibtex not pdflatex. You may want to check bibtex’s log.
