### ISSUE TITLE
Issue with extra fonts

### ISSUE THREAD

**Issue by askming** [xu-cheng/latex-action#72]
Hi,

Thanks for making the latex action. I'm having a trouble in using extra font family (running xelatex) and got some error message as follows:

> Package fontspec Error: The font "Minion Pro" cannot be found.

I added the font file under the working directory but it seems it still can't found or used by the program. Any advice on this?

Thanks!

**Comment by xu-cheng** [comment]
For general questions related to the usage of LaTeX, you can refer to Google or TeX.StackExchange. For example, [this](https://www.overleaf.com/learn/latex/Questions/I_have_a_custom_font_I%27d_like_to_load_to_my_document._How_can_I_do_this%3F) introduces ways to load custom fonts in LaTeX. 

Please only open issue related to this GitHub Action in the future. Thanks.
