### ISSUE TITLE
Rule 'pdflatex' & Maximum Rules

### ISSUE THREAD

**Issue by ineshbose** [xu-cheng/latex-action#76]
This query may not be specific to this action, however, there might be a solution using the inputs that I'm missing.

I'm compiling a document that uses `minted` therefore that needs `--shell-escape` and that's enabled - I don't think that is causing problems. I am using `svg`, therefore that needs Inkscape, there I have added that in `extra_system_packages`. However, it seems that is detecting some changes in the files and re-running `pdflatex` repeatedly, until the limit 5 is crossed and the action fails.

For reference,
this is the run: https://github.com/ineshbose/how-green/runs/4509286198;
this is YAML:  https://github.com/ineshbose/how-green/blob/master/.github/workflows/build-pdf.yml;
this is document: https://github.com/ineshbose/how-green/blob/master/report.tex

I appreciate your help in advance and love how friendly conversations are on other issues on this repository!

**Comment by xu-cheng** [comment]
In your tex, you have https://github.com/ineshbose/how-green/blob/cbd2473930969cd3dffc67b4663b5c358eb65fdc/report.tex#L23, which will generate new svg figure for each run. I think this may be the reason latexmk reruns the complication repeatedly. Could you try to remove this? Ideally, you should just commit logo-black.svg file in your git repo.

**Comment by ineshbose** [comment]
You're right. I preferred to not have a separate version of the logo, but I've come up with two solutions after sleeping over it.

1. Creating the logo during the action by adding
```yml
      - name: Add black logo
        run: |
          sed 's/00D98F/1c1c1c/' assets/logo.svg >assets/logo-black.svg
```

2. Adding a check/safeguard/if-statement in L23
```tex
\immediate\write18{[[ ! -f "assets/logo-black.svg" ]] && sed 's/00D98F/1c1c1c/' assets/logo.svg >assets/logo-black.svg}
```

Thank you very much, and I am now closing this issue!
