### ISSUE TITLE
resulting PDF

### ISSUE THREAD

**Issue by stephenll** [xu-cheng/latex-action#8]
How do you get access to the compiled PDF after using this action?

**Comment by xu-cheng** [comment]
The PDF file will be in the same folder as that of the latex source in the CI environment. It is up to you on whether to upload it to some places. Here are some example.

* You can use https://github.com/actions/upload-artifact to upload it to the workflow tab.
* Or you can use normal shell tools such as scp/git/rsync to upload it anywhere. For example, you can git push it to the `gh-pages` branch in your repo, so you can view it using Github Pages.
