### ISSUE TITLE
Test GitHub Action has been failing

### ISSUE THREAD

**Issue by sadikkuzu** [xu-cheng/latex-action#89]
Hi,

Test GitHub Action has been failing since March 6th
https://github.com/xu-cheng/latex-action/actions/workflows/test.yml

[![GitHub Actions Status](https://github.com/xu-cheng/latex-action/workflows/Test%20Github%20Action/badge.svg)](https://github.com/xu-cheng/latex-action/actions)

**Comment by sadikkuzu** [comment]
![image](https://user-images.githubusercontent.com/23168063/159141070-05c18c93-fd56-480b-9cfb-06826e4960df.png)

**Comment by xu-cheng** [comment]
This issue has been fixed.
