### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by simonbyrne** [xu-cheng/latex-action#9]
I've been seeing this message

```
biber
mv: can't rename '/tmp/install-biber/biber-linux_x86_64-musl': No such file or directory
The command '/bin/sh -c /root/setup.sh' returned a non-zero code: 1
```

e.g. https://github.com/climate-machine/Design-Docs/runs/295852897#step:2:1008

I suspect it's a texlive installation issue?

**Comment by xu-cheng** [comment]
It seems that you are using an old version of this action. Try replace `xu-cheng/latex-action@1.0` to `xu-cheng/latex-action@master`.

**Comment by simonbyrne** [comment]
Ah, I was installing the one github suggested. Not sure why it suggested that version.
