### ISSUE TITLE
Glossary not working

### ISSUE THREAD

**Issue by AC37-rulescommittee** [xu-cheng/latex-action#97]
Hello, 

I try to generate a document with XeLaTex containing a glossary. Here a plain simple example: 

`\documentclass[a4paper,12pt,]{scrartcl}

\usepackage[toc]{glossaries}
\newglossaryentry{computer}
{
    name=computer,
    plural=computers,
    description={is a programmable machine that receives input,
        stores and manipulates data, and provides
        output in a useful format}
}
\makeglossaries

\begin{document}
    \tableofcontents
    \section{TEST}\label{ch:Test}
        In our company we are using \glspl{computer}.
    \begin{appendix}
        \printglossaries
    \end{appendix}
\end{document}`

Running it with the following yml file: 

`name: Github Action for LaTeX
on: [workflow_dispatch]

jobs: 
  build_latex:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LateX document (Run 1)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: glossary_test.tex
          latexmk_use_xelatex: true
      - name: Compile LateX document (Run 2)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: glossary_test.tex
          latexmk_use_xelatex: true
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: glossary_test.pdf`

I don't get the glossary built and have the following message when running XeLaTex: 

`...
(scrartcl)              `\appendix' on input line 18.
No file glossary_test.gls.
[1] (./glossary_test.aux) )
Output written on glossary_test.xdv (1 page, 1488 bytes).
...`

**Comment by xu-cheng** [comment]
See #96
